// Package event describes events that are generated by the repository's operations.
// This information can be used to create rich user interfaces with live updates
// without interceding in regular use of the repository's API
package event
